export const reviewerTypes = [
  { label: "The Drama Queen", description: "Theatrical rants over nothing" },
  { label: "One-Star Sniper", description: "Single stars, no reason" },
  { label: "Karen", description: "Whines, demands the manager" },
  { label: "VIP", description: "Classy, top-tier patron" },
  { label: "Star Legend", description: "Fair, glowing reviews" },
  { label: "No-Show Ninja", description: "Ghosts, slams online" },
  { label: "Nitpicker", description: "Obsesses over tiny flaws" },
  { label: "Rage Typer", description: "All-caps, angry rants" },
  { label: "Bargain Bandit", description: "Wants luxury for free" },
  { label: "Superfan", description: "Loves, promotes your biz" },
  { label: "Clout Chaser", description: "Bashes for social fame" },
  { label: "Coupon Scammer", description: "Demands deals, rates low" },
  { label: "Cheerleader", description: "Heartfelt, uplifting praise" },
  { label: "Troll Lord", description: "Stirs chaos with bad reviews" },
  { label: "Fake Reviewer", description: "Rates, never visited" },
  { label: "Loyal Rockstar", description: "Awesome, fair reviewer" },
  { label: "Meltdown Maven", description: "Small issues, big tantrums" },
  { label: "Discount Diva", description: "Wants freebies, rates low" },
  { label: "Truth Teller", description: "Honest, fair reviewer" },
  { label: "Chaos Starter", description: "Starts review drama" },
  {
    label: "Dory",
    description: "Forgets details, leaves inaccurate reviews (Finding Nemo)",
  },
];
export const businessCategories = [
  { label: "Food and Drink" },
  { label: "Home Services" },
  { label: "Entertainment" },
  { label: "Beauty & Well-Being" },
  { label: "Clothing & Fashion" },
  { label: "Business Services" },
  { label: "Health & Medical" },
  { label: "Electronics & Tech" },
  { label: "Travel & Vacation" },
  { label: "Financial Services" },
  { label: "Automotive" },
  { label: "Construction" },
];
